### PR TITLE
chore: Report file - extend failure message

### PR DESCRIPTION
**Pull request by mp-dthr**
Adding more info for specific metrics into report file. Most of the pipelines work with JUnit reporter, so it would be nice to have meaningful failure messages.

### CODE REVIEW

**Review by na-- — CHANGES_REQUESTED** [review]
I can't comment on the JUnit parts of this, but I can on the k6 ones :sweat_smile: Please don't hardcode the metric names in the script, this won't work with custom metrics or with any built-in metrics we add to k6 in the future.

Instead, use the fact that the metric type is in the `data` that is passed to `handleSummary()`, log it with `JSON.stringify()` to see it contains things like:
```
        "http_req_duration": {
            "contains": "time",
            "values": {
                "avg": 139.853488,
                "min": 139.853488,
                "med": 139.853488,
                "max": 139.853488,
                "p(90)": 139.853488,
                "p(95)": 139.853488
            },
            "type": "trend"
        },
        "http_req_failed": {
            "type": "rate",
            "contains": "default",
            "values": {
                "rate": 0,
                "passes": 0,
                "fails": 1
            }
        },

```

**Comment by mp-dthr** [comment]
Thanks for your comment @na--. Added new changes, so it could be distinguished by metric type.
In case new metric type is introduced, it will add default message as it was until now for all types. In order to cover new types, new condition should be added.

**Review by na-- — APPROVED** [review]
LGTM. 

As a minor nitpick, the metric types probably don't need to be in a constant, given that they are only used once and are unlikely to ever change.

**Review by oleiade — APPROVED** [review]
Looking good, thanks for that 🙇🏻

**Comment by mp-dthr** [comment]
Thank you guys! 🙇 
Seems like the new version is not generated yet, just checked in https://jslib.k6.io/ :
Screenshot 2022-12-22 at 09 46 38

Is anything else that should be done in order to generate a version with these changes?

**Comment by oleiade** [comment]
@mp-dthr indeed, for now, we have to do this manually. I've scheduled to do it later today 👍🏻

**Comment by oleiade** [comment]
@mp-dthr v0.0.3 is now published, and publicly available. Thanks again for your contribution! 🙇🏻

**Pull request merged**
